# Generated by Django 2.0.5 on 2018-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0002_auto_20180621_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='primary_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='secondary_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
