# Generated by Django 2.0.5 on 2018-06-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0003_auto_20180621_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicer.Employee'),
        ),
    ]
