# Generated by Django 2.0.5 on 2018-06-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0005_remove_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
